{
 "title": "Nature Remo",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "現在の電力消費量",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (remo_measured_instantaneous_energy_watt)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "電力消費量",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(name) (remo_measured_instantaneous_energy_watt)"
    }
   ]
  },
  {
   "title": "温度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(name) (remo_temperature)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "湿度",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "avg by(name) (remo_humidity)", "legendFormat": "{{name}}" }
   ]
  }
 ]
}