#!/bin/bash

for target_user in $(cat /etc/cardinal/userlist /etc/cardinal/userlist.d/* | grep ':' | sort | uniq); do
  linux_user=$(echo ${target_user} | cut -d":" -f1)
  github_users=$(echo ${target_user} | cut -d":" -f2)
  if id ${linux_user} &>/dev/null; then
    echo "execute: ${linux_user}"
    if ls /home/${linux_user}/.ssh/authorized_keys &>/dev/null; then
      rm -f /home/${linux_user}/.ssh/authorized_keys
    fi
    for i in $(echo ${github_users} | tr ',' ' '); do
      su - ${linux_user} -c "ssh-import-id gh:${i}"
    done
  else
    echo "${linux_user} is not user."
  fi
done
