#!/bin/bash

for target_user in $(cat /etc/cardinal/userlist /etc/cardinal/userlist.d/* | grep ':' | sort | uniq); do
  linux_user=$(echo ${target_user} | cut -d":" -f1)
  github_users=$(echo ${target_user} | cut -d":" -f2)
  if id ${linux_user} &>/dev/null; then
    echo "execute: ${linux_user}"
    homedir=/home/${linux_user}
    if [ "root" = "${linux_user}" ]; then
      homedir="/root"
    fi
    if ls ${homedir}/.ssh/authorized_keys &>/dev/null; then
      rm -f ${homedir}/.ssh/authorized_keys
    fi
    for i in $(echo ${github_users} | tr ',' ' '); do
      su - ${linux_user} -c "curl -sLo ${homedir}/.ssh/authorized_keys https://github.com/${i}.keys && chmod 600 ${homedir}/.ssh/authorized_keys"
    done
  else
    echo "${linux_user} is not user."
  fi
done
