apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grist

resources:
- namespace.yaml
- onepassword-grist.yaml
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
- ingressroute.yaml