apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grist-data
  namespace: grist
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi