apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grist-data
  labels:
    app.kubernetes.io/name: grist
    app.kubernetes.io/instance: grist
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi