apiVersion: v1
kind: Secret
metadata:
  name: grist-secret
  annotations:
    operator.1password.io/item-path: "vaults/Shared/items/grist"
type: Opaque
data:
  session-secret: "" # This will be populated by 1Password operator