apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions-runner-system

helmCharts:
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.9.3
    releaseName: suzutan-self-hosted
    namespace: actions-runner-system
    valuesFile: values-standard.yaml
  
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.9.3
    releaseName: suzutan-docker
    namespace: actions-runner-system
    valuesFile: values-docker.yaml