apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: github-app-private-key
  namespace: actions-runner-system
spec:
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/GITHUB_APP_PRIVATE_KEY"