apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actions-runner-controller
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - pods/finalizers
      - secrets
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - actions.summerwind.dev
      - actions.github.com
    resources:
      - runners
      - runnerdeployments
      - runnerreplicasets
      - runnersets
      - horizontalrunnerautoscalers
      - ephemeralrunners
      - ephemeralrunnersets
      - autoscalingrunnersets
      - autoscalinglisteners
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - actions.summerwind.dev
      - actions.github.com
    resources:
      - runners/finalizers
      - runnerdeployments/finalizers
      - runnerreplicasets/finalizers
      - runnersets/finalizers
      - horizontalrunnerautoscalers/finalizers
      - ephemeralrunners/finalizers
      - ephemeralrunnersets/finalizers
      - autoscalingrunnersets/finalizers
      - autoscalinglisteners/finalizers
    verbs:
      - update
  - apiGroups:
      - actions.summerwind.dev
      - actions.github.com
    resources:
      - runners/status
      - runnerdeployments/status
      - runnerreplicasets/status
      - runnersets/status
      - horizontalrunnerautoscalers/status
      - ephemeralrunners/status
      - ephemeralrunnersets/status
      - autoscalingrunnersets/status
      - autoscalinglisteners/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: actions-runner-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: actions-runner-controller
subjects:
  - kind: ServiceAccount
    name: actions-runner-controller
    namespace: actions-runner-controller