apiVersion: v1
kind: Service
metadata:
  name: actions-runner-controller-webhook
spec:
  type: ClusterIP
  selector:
    app: actions-runner-controller
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: actions-runner-controller-metrics
spec:
  type: ClusterIP
  selector:
    app: actions-runner-controller
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP