{
 "title": "M5Stack AirQ",
 "tags": [
  "airq",
  "m5stack"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "PM2.5",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airq_pm2_5", "legendFormat": "PM2.5" }
   ]
  },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airq_co2", "legendFormat": "CO2" }
   ]
  },
  {
   "title": "温度",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airq_temperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "湿度",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airq_humidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "PM (粒子状物質)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "airq_pm1_0", "legendFormat": "PM1.0" },
    { "expr": "airq_pm2_5", "legendFormat": "PM2.5" },
    { "expr": "airq_pm4_0", "legendFormat": "PM4.0" },
    { "expr": "airq_pm10_0", "legendFormat": "PM10.0" }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "airq_co2", "legendFormat": "CO2" }
   ]
  },
  {
   "title": "温度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "airq_temperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "湿度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "airq_humidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "VOC Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "airq_voc", "legendFormat": "VOC Index" }
   ]
  },
  {
   "title": "NOx Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "airq_nox", "legendFormat": "NOx Index" }
   ]
  }
 ]
}